export const GET_LIST_SHOPS_REQUEST_START = "GET_LIST_SHOPS_REQUEST_START";

export const GET_LIST_SHOPS_REQUEST_SUCCEEDED =
  "GET_LIST_SHOPS_REQUEST_SUCCEEDED";

export const GET_LIST_SHOPS_REQUEST_FAILED = "GET_LIST_SHOPS_REQUEST_FAILED";
